# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '12.x'
    - run: npm install
    - run: npm run build --if-present
    - run: npm test
    - name: Build and push docker image
      uses: mr-smithers-excellent/docker-build-push@v4
      with:
        image: soup1c/npm-demo-app
        registry: docker.io
        username: ${{secrets.DOCKER_USERNAME}}
        password: ${{secrets.DOCKER_PASSWORD}} 
        
        
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Kubernetes set context
        uses: Azure/k8s-set-context@v1
        with:
          method: kubeconfig
          kubeconfig: ${{secrets.K8S_CONFIG}} 
      - name: kubernetes deploy
        run: |
          kubectl apply -f https://raw.githubusercontent.com/SouP1C/npm-demo-app-coonfig/main/namespace.yaml
          kubectl apply -f https://raw.githubusercontent.com/SouP1C/npm-demo-app-coonfig/main/deployment.yaml
          kubectl apply -f https://raw.githubusercontent.com/SouP1C/npm-demo-app-coonfig/main/hpa.yaml
          kubectl apply -f https://raw.githubusercontent.com/SouP1C/npm-demo-app-coonfig/main/service.yaml
